[workspace]
members = [
    'nimbus-consensus',
    'nimbus-primitives',
    'pallets/aura-style-filter',
    'pallets/author-inherent',
    'pallets/author-slot-filter',
    'parachain-template/runtime',
    'parachain-template/node',
]

[profile.release]
panic = 'unwind'