[workspace]
members = [
	"nimbus-consensus",
	"nimbus-primitives",
	"pallets/aura-style-filter",
	"pallets/author-inherent",
	"pallets/author-slot-filter",
	"allychain-template/node",
	"allychain-template/runtime",
]

[profile.release]
panic = "unwind"
