# This CI Tries to be both simple and effective. It is inspired by:
# https://github.com/marketplace/actions/rust-cache
# https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
# https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

name: Rust Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cargo-check:
    name: Cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        run: rustup show
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find un-copyrighted files
        run: |
          find . -name '*.rs' -not -path "*/allychain-template/*" -exec grep  -H -E -o -c Copyright {} \; | grep ':0' || true
          FILECOUNT=$(find . -name '*.rs' -not -path "*/allychain-template/*" -exec grep  -H -E -o -c  'Copyright'  {} \; | grep -c ':0' || true)
          if [[ $FILECOUNT -eq 0 ]]; then
            true
          else
            false
          fi